import { NFT } from "../store/useNFTStore";
import { generateUniqueId } from "./nft";

export const INITIAL_NFTS: NFT[] = [
  {
    id: generateUniqueId(),
    name: "Cosmic Dragon",
    description: "A majestic dragon soaring through the cosmic void",
    image: "https://dummyimage.com/300x300/6D28D9/ffffff&text=Cosmic+Dragon",
    collection: "Mythical Beasts",
    currentPrice: 500,
    lastPrice: 500,
    ownerId: "marketplace",
    forSale: true,
    forAuction: false,
    forTrade: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUniqueId(),
    name: "Digital Phoenix",
    description: "A phoenix reborn in the digital age",
    image: "https://dummyimage.com/300x300/6D28D9/ffffff&text=Digital+Phoenix",
    collection: "Mythical Beasts",
    currentPrice: 750,
    lastPrice: 750,
    ownerId: "marketplace",
    forSale: true,
    forAuction: false,
    forTrade: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUniqueId(),
    name: "Crystal Unicorn",
    description: "A unicorn crafted from pure crystal",
    image: "https://dummyimage.com/300x300/6D28D9/ffffff&text=Crystal+Unicorn",
    collection: "Mythical Beasts",
    currentPrice: 600,
    lastPrice: 600,
    ownerId: "marketplace",
    forSale: true,
    forAuction: false,
    forTrade: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUniqueId(),
    name: "Mystic Wolf",
    description: "A wolf imbued with ancient mystical powers",
    image: "https://dummyimage.com/300x300/6D28D9/ffffff&text=Mystic+Wolf",
    collection: "Mythical Beasts",
    currentPrice: 550,
    lastPrice: 500,
    ownerId: "marketplace",
    forSale: true,
    forAuction: false,
    forTrade: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateUniqueId(),
    name: "Cyber Griffin",
    description: "A griffin adapted to the digital realm",
    image: "https://dummyimage.com/300x300/6D28D9/ffffff&text=Cyber+Griffin",
    collection: "Mythical Beasts",
    currentPrice: 800,
    lastPrice: 800,
    ownerId: "marketplace",
    forSale: true,
    forAuction: false,
    forTrade: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
